#!/usr/bin/env python3
"""HTML 명명 엔티티 표를 리소스로 만든다.

Confluence 저장 형식은 DTD 없는 XML 인데 본문에는 &nbsp; &mdash; 같은 HTML 엔티티가
그대로 들어 있다(실측: 본문 144개 중 18개). XML 파서는 첫 번째 엔티티에서 죽는다.
그래서 파싱 전에 명명 엔티티를 숫자 참조로 바꾼다 — 그 표가 이 파일이다.

  python3 tools/make-html-entities.py
"""
import html.entities
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "main" / "resources" / "html-entities.properties"

# XML 이 스스로 아는 다섯 개는 건드리지 않는다.
BUILTIN = {"amp", "lt", "gt", "quot", "apos"}

lines = ["# Generated by tools/make-html-entities.py - do not edit.\n"]
for name, codepoint in sorted(html.entities.name2codepoint.items()):
    if name in BUILTIN:
        continue
    lines.append("%s=%d\n" % (name, codepoint))

OUT.write_text("".join(lines), encoding="ascii")
print("%s (%d entries)" % (OUT.relative_to(ROOT), len(lines) - 1))
